name: Disruptiveinnovations
favicon: null
layout_spectrum: 0.8235918306745589
typography_spectrum: 0.12069938890635967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3938798005692661
  lightness: 0.6016564420424402
  saturation: 0.9309385598171502
  rhythmicContrast: 0.7155348772648722
purpose: []
